import turtle

turtle.forward(100)
turtle.right(90)
s = turtle.getscreen()
s.setup(500, 400)
turtle.hideturtle()
t = turtle.Turtle()
t.position()
t.pos()
t.left(90)
t.forward(80)
t.right(30)
t.backward(100)
t.goto(-100, 100)
t.home()
t.circle(10)
t.dot(20)
turtle.bgcolor('#ffffff')
turtle.bgcolor('purple')
